package com.example.model

/** The three on-device "brains" Pip is made of. */
enum class ModelId(
    val title: String,
    val subtitle: String,
    val primaryFunction: String,
    val phaseRole: String
) {
    STT(
        title = "Ears · Vosk speech-to-text",
        subtitle = "vosk-model-small-en-us-0.15 (offline)",
        primaryFunction = "Turns your voice into text on the phone",
        phaseRole = "Loaded only while Pip is listening"
    ),
    LLM(
        title = "Brain · SmolLM2-135M",
        subtitle = "Instruct, 4-bit ONNX (offline)",
        primaryFunction = "Thinks of fractured, inspiring answers",
        phaseRole = "Loaded when thinking, released when idle"
    ),
    TTS(
        title = "Voice · Android text-to-speech",
        subtitle = "Built-in offline voice (no download)",
        primaryFunction = "Speaks Pip's answers out loud",
        phaseRole = "Built into the phone"
    )
}

enum class ModelStatus {
    NOT_DOWNLOADED,
    DOWNLOADING,
    INSTALLING,
    READY,
    FAILED
}

data class ModelItem(
    val id: ModelId,
    val status: ModelStatus = ModelStatus.NOT_DOWNLOADED,
    val downloadedBytes: Long = 0L,
    val totalBytes: Long = 0L,
    val bytesPerSecond: Long = 0L,
    val sizeOnDiskBytes: Long = 0L,
    /** Plain-language reason when [status] is FAILED (never an exception class name). */
    val error: String? = null,
    /** Which file of a multi-file model is being fetched, for display. */
    val currentFile: String = ""
) {
    val progress: Float
        get() = if (totalBytes > 0) (downloadedBytes.toFloat() / totalBytes).coerceIn(0f, 1f) else 0f
}

enum class PipelineStage {
    IDLE,
    LISTENING,    // microphone open, speech-to-text running
    THINKING,     // the language model is working
    SPEAKING,     // Pip is talking (microphone is closed so Pip cannot hear itself)
    INTERRUPTED   // user cut Pip off
}

/** Where an answer really came from. The UI shows this honestly. */
enum class AnswerSource {
    SAFETY,    // a caring, clear answer for a crisis message
    DESIGNED,  // one of Pip's hand-written signature answers
    CACHE,     // asked before
    MODEL,     // generated by the on-device language model
    INSTINCT   // Pip's own pattern brain (model missing, too slow, or off-brand)
}

data class ChatMessage(
    val id: String,
    val userQuery: String,
    val fracturedResponse: String,
    val timestamp: Long = System.currentTimeMillis(),
    val source: AnswerSource = AnswerSource.INSTINCT,
    val thinkMs: Long = 0L,
    val wasSpoken: Boolean = false,
    val wasInterrupted: Boolean = false,
    val isPlaying: Boolean = false
)
